### ISSUE TITLE
sendMessage issue

### ISSUE THREAD

**Issue by Voncoda** [voxeet/android-sdk#2]
**Describe the bug**

Hello, I'm successfully joining a conference without problems 👍.
I wanted to use the "sendMessage" method without success, the other web / android didn't receive anything, maybe I missed something?

**Expected Behaviour**

Web and Android receive a simple string.

**Steps to Reproduce the Problem**

login, create, join, and sendMessage using promises

**Minimalistic code (recommended)**

VoxeetSdk.conference().sendMessage(VoxeetSdk.conference().getConferenceId(), "my string");

**Specifications**

- Android Emulator revision 29.2.1 with API 29
- VoxeetSdk version 2.0.69.7 (I tried my best to have the last one, I don't really know where to find it)
- Android Studio

**Comment by codlab** [comment]
sendMessage is a promise that your sample code does not resolve. Hence no message sent. If you resolve the promise it'll be sent 👍
